#!/usr/bin/env zsh

# suppress "zsh no matches found"
setopt +o nomatch
autoload -U age

cd ~/.xmonad

AGEREF=$(stat -c %y xmonad-x86_64-linux)
OLD=$(ls *(+age) | grep -v xmonad-x86_64-linux | grep -E '*.hs' | wc -l)

[[ $OLD > 0 ]] && . scripts/compile
